[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6.6"
sysinfo = "0.35.2"
serde = { version = "1.0.219", features = ["derive"] }
whoami = "1.6.0"
async-std = "1.13.1"
